<br />
<table  width="760" border="0" cellpadding="0" cellspacing="0">			
	<tr>
		<td align="center">
			<!--<hr color="006600" size="1">
			<font class="boldtextGreen">© The Canadian Centre for Studies of Children at Risk</font>
			Changed May 24, 2004   
      
      <font class="boldTextGreen">&copy; Offord Centre for Child Studies</font>
      changed 2009
			-->
      <a class="regLinkGreen" href="http://www.offordcentre.com/readiness/index.html">&copy; Offord Centre for Child Studies</a>
			<br />
			<font class="boldTextGreen">McMaster University &amp; Hamilton Health Sciences, Hamilton ON, Canada</font>
			<br />
			<font class="boldTextGreen">Tel.(905)525-9141 27051</font>
		</td>
	</tr>
</table>
<!-- #include virtual="/shared/visitor_info.asp" -->

