<br />
<table  width="480" border="0" cellpadding="0" cellspacing="0">			
	<tr>
		<td align="center">
			<!--<hr color="006600" size="1">
			<font class="boldtextGreen">© The Canadian Centre for Studies of Children at Risk</font>
			Changed May 24, 2004
			-->
			<font class="boldtextGreen">&copy; Offord Centre for Child Studies</font>
			<br />
			<font class="boldtextGreen">McMaster University & Hamilton Health Sciences, Hamilton ON, Canada</font>
			<br />
			<font class="boldtextGreen">Tel.(905)521-2100, ext.74377</font>
		</td>
	</tr>
</table>